server:
  port: 9000
zuul:
  routes:
    client:
      path: /client/**
      url: http://localhost:7000
    resource:
      path: /resource/**
      url: http://localhost:8000
logging:
  level:
    org:
      springframework:
        web: DEGUG